#!/usr/bin/env bash

project_name=""
project_package_path=""

generate_project_package_path_from_reversed_domain(){
  project_package_path=$(sed 's/\./\//g' <<< $1);
}

help_information(){
  echo -e 'For more information type: \e[1mmkprj_dir --help\e[0m';
}

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo -e "\n"
      echo -e "\e[1mName:\e[0m"
      echo -e "\tmkprj_dir - project directories creator.\n";
      
      echo -e "\e[1mSynopsis:\e[0m";
      echo -e "\t\e[1mmkprj_dir\e[0m [OPTION]... NAME\n";
      
      echo -e "\e[1mOptions:\e[0m"
      echo -e "\t\e[1m-d, --domain\e[0m\treverse domain notation e.g. pl.com.muca";
      echo -e "\t\e[1m-n, --name \e[0m\tname of the project e.g. battleships";
      exit 0
      ;;
  -r)
    shift
    if test $# -gt 0; then
      reversed_domain=$1;
      generate_project_package_path_from_reversed_domain ${reversed_domain}
    else
      echo -e 'Reversed domain was not specified after \e[1m-r\e[0m option';
      help_information  
      exit 1;
    fi
    shift
    ;;
  --reversed_domain*)
    reversed_domain=$(sed 's/^[^=]*=//g' <<< $1); 
    generate_project_package_path_from_reversed_domain ${reversed_domain}
    shift
    ;;
  -n)
    shift
    if test $# -gt 0; then
      project_name=$1
    else
      echo -e 'Project name was not specified after \e[1m-n\e[0m option';
      help_information  
      exit 1;
    fi
    shift
    ;;
  --name*)
    project_name=$(sed 's/^[^=]*=//g' <<< $1);
    shift
    ;;
   *)
     break;
     ;;
  esac
done

if [[ -d "${project_name}" ]];then
  echo -e "Directory \e[1m${project_name}\e[0m already exists.";
  exit 1;
elif [[ -z "${project_name}" ]];then
  echo -e 'Please specify project name.'
  help_information  
  exit 1;
else
  mkdir -p "${project_name}/src/main/java/${project_package_path}"
  mkdir -p "${project_name}/src/test/java/${project_package_path}"
  mkdir -p "${project_name}/src/main/resources"
fi

echo -e "Project \e[1m${project_name}\e[0m created successfully.";
echo "Project package path: ${project_package_path}";
