#!/bin/bash
path_by_domain="/pl/com/muca";
set -e
if [ "x$1" = "x" ];then
	echo "Please insert the project name.";
	exit 1;
elif [ -d $1 ];then
	echo "\"${x}\" directory already exits. ";
	exit 1;
else
	mkdir $1
	cd $1
	mkdir -p "src/main/java/${path_by_domain}"
	mkdir -p "src/test/java/${path_by_domain}"
  	mkdir -p "src/main/resources"
fi
